services:
  expedition25-api:
    image: dixennaxos/expedition25:api
    ports:
      - "8000:8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.expedition25-api.rule=Host(`skyexplorer-api.dixen.fr`)"
      - "traefik.http.routers.expedition25-api.entrypoints=websecure"
      - "traefik.http.routers.expedition25-api.tls.certresolver=myresolver"
    networks:
      - traefik
    volumes:
      - "./api.env:/app/.env"
  expedition25-front:
    image: dixennaxos/expedition25:front
    ports:
      - "8081:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.expedition25-front.rule=Host(`skyexplorer.dixen.fr`)"
      - "traefik.http.routers.expedition25-front.entrypoints=websecure"
      - "traefik.http.routers.expedition25-front.tls.certresolver=myresolver"
    networks:
      - traefik
    volumes:
      - "./front.env:/usr/share/nginx/html/.env"
networks:
  traefik:
    external: true
